# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insides',
            name='concordance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insides',
            name='maps',
            field=models.BooleanField(),
        ),
    ]
