# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180725_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='insides',
            name='short_description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
