# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_insides_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insides',
            name='images',
        ),
    ]
