# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_insides_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='leather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('amimal', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=50)),
                ('source', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
