# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leather'),
    ]

    operations = [
        migrations.AddField(
            model_name='leather',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
